#!/bin/bash
# depends on fzf(https://github.com/junegunn/fzf)

function repogo(){
    project_name=$1
    out=$(repo list | grep "${project_name}")
    if [ -n ${out} ];then
        project_path=$(echo "${out}" | awk '{print $1}')
        echo "cd ${project_path}"
        cd "${project_path}"
    fi
}

function repofzf(){
    project_name=$1
    out=$(repo list | fzf -q "${project_name}")
    if [ -n ${out} ];then
        project_path=$(echo "${out}" | awk '{print $1}')
        echo "cd ${project_path}"
        cd "${project_path}"
    fi
}

function cdlast() {
    ls -rt | tail -1 | xsel -b
    dir_name=$(xsel -b)
    cd ${dir_name}
}

function cplast() {
    ls -rt | tail -1 | tr -d '\n' | xsel -b
}

function alertover () {
    content=$*
    # alertover
    curl -s \
         --form-string "source=s-138cdc2f-8624-461c-8cdf-3ebf5931" \
         --form-string "receiver=g-364ec0e4-5c27-4fbb-a899-040eea16" \
         --form-string "content=${content}" \
         https://api.alertover.com/v1/alert
}

alias flashap="
fastboot flash boot boot.img;
fastboot flash system system.img;
fastboot flash persist persist.img;
fastboot flash userdata userdata.img;
fastboot reboot"

alias gg='git log --oneline --abbrev-commit --all --graph --decorate --color'
alias gd="git diff"
alias gc="git clone"
alias ga="git add"
alias gbd="git branch -D"
alias gst="git status"
alias gca="git commit -a -m"
alias gpt="git push --tags"
alias gp="git push"
alias gpr="git pull-request"
alias grh="git reset --hard"
alias gb="git branch"
alias gcob="git checkout -b"
alias gco="git checkout"
alias gba="git branch -a"
alias gcp="git cherry-pick"
alias gl="git log --pretty='format:%Cgreen%h%Creset %an - %s' --graph"
alias docs="rm -fr /tmp/docs && cp -fr docs /tmp/docs && git checkout gh-pages && cp -fr /tmp/docs/* ."
alias gpom="git pull origin master"
alias gcd='cd "`git rev-parse --show-toplevel`"'
alias gdmb='git delete-merged-branches'
